import json
import os
import boto3
from pathlib import Path


# ============================================================
# CONFIG
# ============================================================

# Project root:
# mlops-aws-learning/
#
# download_model.py is located at:
# src/serving/deployment/download_model.py
#
# parents[0] = deployment
# parents[1] = serving
# parents[2] = src
# parents[3] = mlops-aws-learning
PROJECT_ROOT = Path(__file__).resolve().parents[3]


# selected_model.json generated by select_model.py
SELECTED_MODEL_FILE = PROJECT_ROOT / "selected_model.json"


# Local directory where the selected model will be downloaded
MODEL_DIR = PROJECT_ROOT / "deployment" / "model"


# AWS configuration
BUCKET_NAME = "telco-mlops-yourname-2026"
AWS_PROFILE = "aws-mlops-project"


# ============================================================
# DOWNLOAD SELECTED MODEL
# ============================================================

def download_model():

    print("\n" + "=" * 60)
    print("🚀 DOWNLOADING SELECTED MODEL")
    print("=" * 60)

    # --------------------------------------------------------
    # 1. Check selected_model.json
    # --------------------------------------------------------

    print("\n🔎 Looking for selected_model.json...")
    print(f"   Path: {SELECTED_MODEL_FILE}")

    if not SELECTED_MODEL_FILE.exists():

        raise FileNotFoundError(
            f"\n❌ selected_model.json not found:\n"
            f"   {SELECTED_MODEL_FILE}\n\n"
            f"Run select_model.py first."
        )

    print("   ✅ selected_model.json found")

    # --------------------------------------------------------
    # 2. Read selected_model.json
    # --------------------------------------------------------

    with open(SELECTED_MODEL_FILE, "r") as f:
        selected_model = json.load(f)

    # --------------------------------------------------------
    # 3. Extract selected model information
    # --------------------------------------------------------

    model_name = selected_model["model_name"]
    run_id = selected_model["run_id"]
    version = selected_model["version"]
    roc_auc = selected_model["roc_auc"]

    print("\n📦 SELECTED MODEL")
    print("-" * 60)

    print(f"Model     : {model_name}")
    print(f"Version   : {version}")
    print(f"Run ID    : {run_id}")
    print(f"ROC-AUC   : {roc_auc:.3f}")

    # --------------------------------------------------------
    # 4. Build S3 prefix dynamically
    # --------------------------------------------------------

    s3_prefix = (
        f"models/{model_name}/run-{run_id}/"
    )

    s3_base_path = (
        f"s3://{BUCKET_NAME}/{s3_prefix}"
    )

    print("\n☁️ S3 MODEL LOCATION")
    print("-" * 60)
    print(s3_base_path)

    # --------------------------------------------------------
    # 5. Create local deployment directory
    # --------------------------------------------------------

    MODEL_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    print("\n📁 Local model directory")
    print("-" * 60)
    print(MODEL_DIR)

    # --------------------------------------------------------
    # 6. Create AWS session
    # --------------------------------------------------------

    print("\n🔐 Connecting to AWS...")
    print(f"   Profile: {AWS_PROFILE}")

    try:

        session = boto3.Session(
            profile_name=AWS_PROFILE
        )

        s3 = session.client("s3")

        # Test AWS credentials
        sts = session.client("sts")
        identity = sts.get_caller_identity()

        print("   ✅ AWS credentials verified")
        print(f"   Account: {identity['Account']}")

    except Exception as e:

        raise Exception(
            f"\n❌ Failed to connect to AWS using profile "
            f"'{AWS_PROFILE}'.\n"
            f"Make sure you have logged in/configured the profile.\n\n"
            f"{e}"
        )

    # --------------------------------------------------------
    # 7. Files required by FastAPI
    # --------------------------------------------------------

    files = [
        "model.pkl",
        "feature_columns.json",
        "model_metadata.json"
    ]

    # --------------------------------------------------------
    # 8. Download each file
    # --------------------------------------------------------

    print("\n" + "=" * 60)
    print("⬇️ DOWNLOADING MODEL FILES")
    print("=" * 60)

    for filename in files:

        s3_key = f"{s3_prefix}{filename}"

        local_path = MODEL_DIR / filename

        print(f"\n⬇️ Downloading: {filename}")
        print(f"   S3: s3://{BUCKET_NAME}/{s3_key}")

        try:

            s3.download_file(
                BUCKET_NAME,
                s3_key,
                str(local_path)
            )

            print(
                f"   ✅ Saved: {local_path}"
            )

        except Exception as e:

            raise Exception(
                f"\n❌ Failed to download:\n"
                f"   s3://{BUCKET_NAME}/{s3_key}\n\n"
                f"Error:\n"
                f"   {e}"
            )

    # --------------------------------------------------------
    # 9. Verify downloaded files
    # --------------------------------------------------------

    print("\n" + "=" * 60)
    print("🔍 VERIFYING DOWNLOADED FILES")
    print("=" * 60)

    for filename in files:

        local_path = MODEL_DIR / filename

        if local_path.exists():

            size = local_path.stat().st_size

            print(
                f"   ✅ {filename} "
                f"({size:,} bytes)"
            )

        else:

            print(
                f"   ❌ {filename} NOT FOUND"
            )

    # --------------------------------------------------------
    # 10. Final success message
    # --------------------------------------------------------

    print("\n" + "=" * 60)
    print("✅ MODEL DOWNLOAD COMPLETE")
    print("=" * 60)

    print(f"\nModel       : {model_name}")
    print(f"Version     : {version}")
    print(f"Run ID      : {run_id}")
    print(f"ROC-AUC     : {roc_auc:.3f}")
    print(f"Threshold   : 0.800")

    print("\n☁️ S3 location:")
    print(s3_base_path)

    print("\n📁 Local deployment directory:")
    print(MODEL_DIR)

    print("\n📦 Downloaded files:")

    for filename in files:
        print(f"   ✅ {filename}")

    print("\n🚀 Selected model is ready for FastAPI deployment!")


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    download_model()